# Generated by Django 5.2 on 2025-04-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('idinvoice', models.AutoField(db_column='idInvoice', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Invoice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('idoffer', models.AutoField(db_column='idOffer', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('offerstatus', models.JSONField(blank=True, db_column='offerStatus', null=True)),
            ],
            options={
                'db_table': 'Offer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orderdata',
            fields=[
                ('idorder', models.AutoField(db_column='idOrder', primary_key=True, serialize=False)),
                ('orderdate', models.DateTimeField(blank=True, db_column='orderDate', null=True)),
            ],
            options={
                'db_table': 'OrderData',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idproduct', models.AutoField(db_column='idProduct', primary_key=True, serialize=False)),
                ('titletitle', models.CharField(blank=True, max_length=12, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Productorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('productorderstatus', models.JSONField(blank=True, db_column='productOrderStatus', null=True)),
            ],
            options={
                'db_table': 'ProductOrder',
                'managed': True,
            },
        ),
    ]
