# Generated by Django 5.2 on 2025-04-15 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='iduser',
            field=models.ForeignKey(db_column='idUser', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='idorder',
            field=models.OneToOneField(db_column='idOrder', on_delete=django.db.models.deletion.DO_NOTHING, to='commandes.orderdata'),
        ),
        migrations.AddField(
            model_name='offer',
            name='idproduct',
            field=models.ForeignKey(blank=True, db_column='idProduct', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commandes.product'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='idoffer',
            field=models.ForeignKey(db_column='idOffer', on_delete=django.db.models.deletion.DO_NOTHING, related_name='productorder_idoffer_set', to='commandes.offer'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='idorder',
            field=models.ForeignKey(db_column='idOrder', on_delete=django.db.models.deletion.DO_NOTHING, to='commandes.orderdata'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='idproduct',
            field=models.ForeignKey(db_column='idProduct', on_delete=django.db.models.deletion.DO_NOTHING, to='commandes.offer'),
        ),
        migrations.AlterUniqueTogether(
            name='productorder',
            unique_together={('idorder', 'idproduct', 'idoffer')},
        ),
    ]
