# Generated by Django 5.2 on 2025-04-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_rename_titletitle_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offerstatus',
            field=models.BooleanField(default=True),
        ),
    ]
