# Generated by Django 5.2 on 2025-04-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_alter_offer_offerstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='title',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
