# Generated by Django 5.2 on 2025-04-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0007_offer_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productorder',
            unique_together={('idorder', 'idoffer')},
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='idproduct',
        ),
    ]
