# Generated by Django 5.2 on 2025-04-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0008_alter_productorder_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
