# Generated by Django 5.2 on 2025-04-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0009_offer_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='title',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='productorder',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
