# Generated by Django 5.2 on 2025-04-15 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0010_rename_title_productorder_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='idproduct',
            field=models.ForeignKey(db_column='idProduct', on_delete=django.db.models.deletion.DO_NOTHING, to='commandes.product'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='orderdate',
            field=models.DateTimeField(db_column='orderDate'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=12),
        ),
    ]
