# Generated by Django 5.2 on 2025-04-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_alter_users_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True, 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RenameField(
            model_name='users',
            old_name='tokkengoogle',
            new_name='tokkenGoogle',
        ),
    ]
