# Generated by Django 5.2 on 2025-04-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_alter_users_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='domain',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phonenum',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='lastname',
        ),
        migrations.AddField(
            model_name='contact',
            name='google_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='location_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
