# Generated by Django 5.2 on 2025-04-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0009_rename_website_contact_site_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
