# Generated by Django 5.2 on 2025-04-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0010_alter_contact_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='businessstatus',
            new_name='business_status',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='postalcode',
            new_name='postal_code',
        ),
    ]
