# Generated by Django 5.2 on 2025-04-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0013_alter_contact_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='businessstatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
