# Generated by Django 5.2 on 2025-04-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0015_alter_contact_email_alter_contact_idcontact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
