# Generated by Django 5.2 on 2025-04-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0016_alter_contact_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailsent',
            options={'managed': True, 'verbose_name': 'MailSent', 'verbose_name_plural': 'MailSent'},
        ),
    ]
