# Generated by Django 5.2 on 2025-04-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0017_alter_mailsent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mailbalance',
            field=models.IntegerField(blank=True, db_column='mailBalance', default=0, null=True),
        ),
    ]
