# Generated by Django 5.2 on 2025-05-05 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0020_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('idDomain', models.AutoField(primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'db_table': 'Domains',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.domain'),
            preserve_default=False,
        ),
    ]
