# Generated by Django 5.2 on 2025-05-05 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0022_remove_contact_category_alter_contact_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='idDomain',
            new_name='id',
        ),
    ]
