# Generated by Django 5.2 on 2025-05-05 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0023_rename_iddomain_domain_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='id',
            new_name='idDomain',
        ),
    ]
